[package]
name = "api-foundation"
version = "0.1.0"
edition = "2024"

[dependencies]
aip-160 = "0.1.5"
base64 = "0.23"
bitcode = "0.6"
thiserror = "2.0"

[dev-dependencies]
diesel = { version = "2.2", features = ["postgres"] }
testcontainers-modules = { version = "0.15", features = ["postgres"] }
tokio = { version = "1", features = ["full"] }
